name: DevSecOps Java Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Setup Java
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    # 3. Build
    - name: Compile
      run: |
        mkdir -p bin
        javac -d bin Main.java model/*.java service/*.java utils/*.java

    # 4. SonarCloud (SAST)
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=bipraraksha1995_calculator
          -Dsonar.organization=bipraraksha1995
          -Dsonar.sources=.
          -Dsonar.java.binaries=bin
          -Dsonar.exclusions=bin/**

    # 5. Snyk (SCA)
    - name: Setup Snyk
      uses: snyk/actions/setup@master

    - name: Snyk Dependency Scan
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk test || true

    # 6. Trivy Scan
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: .
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH

    # 7. Run App
    - name: Run Test
      run: echo "5" | java -cp bin Main
